### ISSUE TITLE
[NiFi Registry] Permission error for `auth-conf` on startup

### ISSUE THREAD

**Issue by jrebmann** [dysnix/charts#284]
When deploying the NiFi Registry, a permission error may occur on the `auth-conf` folder.

This is due to a [bug in helm chart](https://github.com/dysnix/charts/blob/eb70bc4270a4a6b491bc9cf3850b7e907e898c6d/dysnix/nifi-registry/templates/statefulset.yaml#L33) which omits the setting of permissions on this folder.

Either the permissions on this folder have to be set manually once, or the folder has to be added to the `initContainers` script.

**Comment by saxcorp** [comment]
I have the same issue and un try to  create the folder on the initContainers, but. it's not work. Someone could provide a example?

**Comment by jrebmann** [comment]
Hi @saxcorp,

it's not about the creation of the folder, but about the permissions.

Just add the folder path to the [`chmod` statement](https://github.com/dysnix/charts/blob/eb70bc4270a4a6b491bc9cf3850b7e907e898c6d/dysnix/nifi-registry/templates/statefulset.yaml#L37C1-L42C68):

```yaml
          command:
            - chown
            - -R
            - 1000:1000
            - /opt/nifi-registry/nifi-registry-current/database
            - /opt/nifi-registry/nifi-registry-current/flow_storage
            - /opt/nifi-registry/nifi-registry-current/auth-conf
```

This worked for me. Hopefully it will for you too.

**Comment by santos-edu** [comment]
Hello, @jrebmann, how are you?

First, thanks for the tips on auth-conf.
If you can, I would like to ask you to share your chart.
Because I still face problems enabling security, with or without CertManager.

**Comment by Evan-Benavides** [comment]
I've been having this issue too where the following security config in values.yaml:

`security:
  # Disabled by default (following the principle of least astonishment)
  enabled: true
  needClientAuth: false
  httpsHost: "0.0.0.0"
  httpsPort: 18443
  admin: "Initial Administrator"
  persistence:
  # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 1Gi
  # ConfigMap with users.xml and authorizations.xml keys; note that these
  # settings will override the admin: key above if present
  authConf:
`
results in the following error:

`│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut [java.io.FileNotFoundException: ./auth-conf/users.xml (Permission denied)]                                                                    │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.file.FileUserGroupProvider.onConfigured(FileUserGroupProvider.java:145)                │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.AuthorizerFactory.getAuthorizer(AuthorizerFactory.java:191)                            │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     ... 108 common frames omitted                                                                                                             │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut Caused by: javax.xml.bind.JAXBException: null                                                                                                 │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:108)                                                 │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.file.FileUserGroupProvider.saveTenants(FileUserGroupProvider.java:596)                 │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.file.FileUserGroupProvider.onConfigured(FileUserGroupProvider.java:135)                │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     ... 109 common frames omitted                                                                                                             │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut Caused by: java.io.FileNotFoundException: ./auth-conf/users.xml (Permission denied)                                                           │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.open0(Native Method)                                                                                          │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.open(FileOutputStream.java:270)                                                                               │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.<init>(FileOutputStream.java:213)                                                                             │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.<init>(FileOutputStream.java:162)                                                                             │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:101)                                                 │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     ... 111 common frames omitted                                                                                                             │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut 2025-02-24 16:25:52,436 INFO [Thread-1] org.apache.nifi.registry.NiFiRegistry Initiating shutdown of Jetty web server...                      │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut 2025-02-24 16:25:52,441 INFO [Thread-1] o.eclipse.jetty.server.AbstractConnector Stopped ServerConnector@23bb8443{SSL, (ssl, http/1.1)}{0.0.0 │
│ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut 2025-02-24 16:25:52,441 INFO [Thread-1] org.eclipse.jetty.server.session node0 Stopped scavenging                                             │
│ nifi-registry 2025-02-24 16:25:52,870 INFO [main] o.a.n.registry.bootstrap.RunNiFiRegistry NiFi Registry never started. Will not restart NiFi Registry`

If I add `/opt/nifi-registry/nifi-registry-current/auth-conf` to the chown statement in the initContainers script it then results in the following error:

`take-data-dir-ownership chown: /opt/nifi-registry/nifi-registry-current/auth-conf: No such file or directory`

It seems like the issue is that the auth-conf configmap isn't being created. Do I need to manually create this or am I supposed to run the `02-configmaps.sh` script before running the helm install?

**Comment by Conafly** [comment]
> I've been having this issue too where the following security config in values.yaml:
> 
> ```
> security:
>   # Disabled by default (following the principle of least astonishment)
>   enabled: true
>   needClientAuth: false
>   httpsHost: "0.0.0.0"
>   httpsPort: 18443
>   admin: "Initial Administrator"
>   persistence:
>   # storageClass: "-"
>     accessMode: ReadWriteOnce
>     size: 1Gi
>   # ConfigMap with users.xml and authorizations.xml keys; note that these
>   # settings will override the admin: key above if present
>   authConf:
> ```
> 
> results in the following error:
> 
> ```
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut [java.io.FileNotFoundException: ./auth-conf/users.xml (Permission denied)]                                                                    │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.file.FileUserGroupProvider.onConfigured(FileUserGroupProvider.java:145)                │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.AuthorizerFactory.getAuthorizer(AuthorizerFactory.java:191)                            │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     ... 108 common frames omitted                                                                                                             │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut Caused by: javax.xml.bind.JAXBException: null                                                                                                 │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:108)                                                 │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.file.FileUserGroupProvider.saveTenants(FileUserGroupProvider.java:596)                 │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.file.FileUserGroupProvider.onConfigured(FileUserGroupProvider.java:135)                │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     ... 109 common frames omitted                                                                                                             │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut Caused by: java.io.FileNotFoundException: ./auth-conf/users.xml (Permission denied)                                                           │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.open0(Native Method)                                                                                          │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.open(FileOutputStream.java:270)                                                                               │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.<init>(FileOutputStream.java:213)                                                                             │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.<init>(FileOutputStream.java:162)                                                                             │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:101)                                                 │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     ... 111 common frames omitted                                                                                                             │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut 2025-02-24 16:25:52,436 INFO [Thread-1] org.apache.nifi.registry.NiFiRegistry Initiating shutdown of Jetty web server...                      │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut 2025-02-24 16:25:52,441 INFO [Thread-1] o.eclipse.jetty.server.AbstractConnector Stopped ServerConnector@23bb8443{SSL, (ssl, http/1.1)}{0.0.0 │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut 2025-02-24 16:25:52,441 INFO [Thread-1] org.eclipse.jetty.server.session node0 Stopped scavenging                                             │
> │ nifi-registry 2025-02-24 16:25:52,870 INFO [main] o.a.n.registry.bootstrap.RunNiFiRegistry NiFi Registry never started. Will not restart NiFi Registry
> ```
> 
> If I add `/opt/nifi-registry/nifi-registry-current/auth-conf` to the chown statement in the initContainers script it then results in the following error:
> 
> `take-data-dir-ownership chown: /opt/nifi-registry/nifi-registry-current/auth-conf: No such file or directory`
> 
> It seems like the issue is that the auth-conf configmap isn't being created. Do I need to manually create this or am I supposed to run the `02-configmaps.sh` script before running the helm install?
> 
> Edit: After further review, I see now that the statefulset.yaml assumes the auth-conf configmap already exists so the script should be used. Alternatively, I assume a configmap.yaml could be created to handle the creation.

I was facing the same issue on the permissions regarding the `auth-conf` directory. Running the initial startup without specifying  anything on `podSecurityContext`, the`auth-conf` directory was missing the write permission on `group`, it was `drwxr-xr-x`. When was created using `podSecurityContext` as root, i didn't have the problem (for obvious reasons). But specifying `user`, `group` and `fsgroup` as 1000, solved the permission problem for me

**Comment by Conafly** [comment]
> I've been having this issue too where the following security config in values.yaml:
> 
> ```
> security:
>   # Disabled by default (following the principle of least astonishment)
>   enabled: true
>   needClientAuth: false
>   httpsHost: "0.0.0.0"
>   httpsPort: 18443
>   admin: "Initial Administrator"
>   persistence:
>   # storageClass: "-"
>     accessMode: ReadWriteOnce
>     size: 1Gi
>   # ConfigMap with users.xml and authorizations.xml keys; note that these
>   # settings will override the admin: key above if present
>   authConf:
> ```
> 
> results in the following error:
> 
> ```
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut [java.io.FileNotFoundException: ./auth-conf/users.xml (Permission denied)]                                                                    │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.file.FileUserGroupProvider.onConfigured(FileUserGroupProvider.java:145)                │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.AuthorizerFactory.getAuthorizer(AuthorizerFactory.java:191)                            │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     ... 108 common frames omitted                                                                                                             │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut Caused by: javax.xml.bind.JAXBException: null                                                                                                 │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:108)                                                 │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.file.FileUserGroupProvider.saveTenants(FileUserGroupProvider.java:596)                 │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at org.apache.nifi.registry.security.authorization.file.FileUserGroupProvider.onConfigured(FileUserGroupProvider.java:135)                │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     ... 109 common frames omitted                                                                                                             │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut Caused by: java.io.FileNotFoundException: ./auth-conf/users.xml (Permission denied)                                                           │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.open0(Native Method)                                                                                          │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.open(FileOutputStream.java:270)                                                                               │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.<init>(FileOutputStream.java:213)                                                                             │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at java.io.FileOutputStream.<init>(FileOutputStream.java:162)                                                                             │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:101)                                                 │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut     ... 111 common frames omitted                                                                                                             │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut 2025-02-24 16:25:52,436 INFO [Thread-1] org.apache.nifi.registry.NiFiRegistry Initiating shutdown of Jetty web server...                      │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut 2025-02-24 16:25:52,441 INFO [Thread-1] o.eclipse.jetty.server.AbstractConnector Stopped ServerConnector@23bb8443{SSL, (ssl, http/1.1)}{0.0.0 │
> │ nifi-registry 2025-02-24 16:25:52,442 INFO [NiFi logging handler] org.apache.nifi.registry.StdOut 2025-02-24 16:25:52,441 INFO [Thread-1] org.eclipse.jetty.server.session node0 Stopped scavenging                                             │
> │ nifi-registry 2025-02-24 16:25:52,870 INFO [main] o.a.n.registry.bootstrap.RunNiFiRegistry NiFi Registry never started. Will not restart NiFi Registry
> ```
> 
> If I add `/opt/nifi-registry/nifi-registry-current/auth-conf` to the chown statement in the initContainers script it then results in the following error:
> 
> `take-data-dir-ownership chown: /opt/nifi-registry/nifi-registry-current/auth-conf: No such file or directory`
> 
> It seems like the issue is that the auth-conf configmap isn't being created. Do I need to manually create this or am I supposed to run the `02-configmaps.sh` script before running the helm install?
> 
> Edit: After further review, I see now that the statefulset.yaml assumes the auth-conf configmap already exists so the script should be used. Alternatively, I assume a configmap.yaml could be created to handle the creation.

I was having issue with permission with the `auth-conf` directory, but after uncommenting the `podSecurityContext` and setting `fsGroup` ID on values, it solved for me.

**Comment by matus-cuper** [comment]
As @Conafly  mentioned above, setting `fsGroup` worked for me as below

```
podSecurityContext:
  fsGroup: 1000
```
